// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FFmpegWebAPI.Models;

public partial class Camera
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public int Index { get; set; }

    public string Description { get; set; }

    public string IpAddress { get; set; }

    public int Port { get; set; }

    public string RtspUrl { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int EndpointStatus { get; set; }

    public int Type { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CameraRecognition> CameraRecognitions { get; set; } = new List<CameraRecognition>();

    public virtual ICollection<GroupCamera> GroupCameras { get; set; } = new List<GroupCamera>();
}