// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FFmpegWebAPI.Models;

public partial class GroupCamera
{
    public int Id { get; set; }

    public int CameraId { get; set; }

    public int GroupId { get; set; }

    public virtual Camera Camera { get; set; }

    public virtual Group Group { get; set; }
}