// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FFmpegWebAPI.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public bool InternalUse { get; set; }

    public virtual ICollection<GroupCamera> GroupCameras { get; set; } = new List<GroupCamera>();
}