// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetaData.Context;

public partial class CameraBusiness
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public int CameraId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Business Business { get; set; }

    public virtual Camera Camera { get; set; }
}