// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetaData.Context;

public partial class ConcatVideoCamera
{
    public int Id { get; set; }

    public Guid Gid { get; set; }

    public DateTime BeginDate { get; set; }

    public DateTime EndDate { get; set; }

    public string VideoUri { get; set; }

    public int Status { get; set; }

    public int CameraId { get; set; }
}