// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MetaData.Context;
using Microsoft.EntityFrameworkCore;

namespace MetaData.Context
{
    public partial class IOTContext : DbContext
    {
        public IOTContext(DbContextOptions<IOTContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Camera> Cameras { get; set; }

        public virtual DbSet<ConcatVideoCamera> ConcatVideoCameras { get; set; }

        public virtual DbSet<Business> Businesses { get; set; }

        public virtual DbSet<CameraBusiness> CameraBusinesses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasDefaultSchema("cmrs")
                .UseCollation("Latin1_General_100_CI_AS_SC");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

